### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Matthew-Bustamante** [SampleShare/SampleShare#11]
### User Profile
**User Story**
Users should have a profile that contains the user's photo, number of followers, posts they've created, and display bio.  The user should also be able to customize their profile at will

### Requirements

- The profile should be its own page on the site 
- The profile should be accessible on the homepage via a link
- The profile should display the user's photo, number of followers, posts, and bio
- The user should be able to change the profile's photo and bio
- Any changes made to the profile should be updated in the database
- Profiles should also be made public for other users to view.

**Comment by chrispugliese** [comment]
Add edit profile function to profile for authenticated users

**Comment by chrispugliese** [comment]
create profile, have register form to createprofile, then submit to profile
