### ISSUE TITLE
Sample Player

### ISSUE THREAD

**Issue by Matthew-Bustamante** [SampleShare/SampleShare#13]
### Sample Player
**User Story**
Users should be able to play the media of a music sample

### Requirements
- There should be a separate page to play samples
- If a user wants to play the media contents of a sample the system should redirect them to sample player page and the site should read a sample's info from the Samples table.
- Using the local file path the site should be able to play the media of that sample

**Comment by saul178** [comment]
playsound package isn't as great as i would have liked, I am gonna look into the html equivalent so that the audio plays on the client side instead of server side. I'll see how it goes.

**Comment by saul178** [comment]
currently i got howler.js to work with all public samples that are uploaded. There is only a basic play and pause toggle for each sample. it looks gross but right now i just care about the functionality.
