### ISSUE TITLE
Searching For Users & Samples

### ISSUE THREAD

**Issue by Matthew-Bustamante** [SampleShare/SampleShare#19]
### Searching For Users & Samples
**User Story**
Users should be able to search for other users and for samples on the platform

### Requirements
-  There should be a search bar on the homepage 
-  When the user uses the search bar they should be able to search for a user's username, or for a public sample name.
- The platform should query the user-profiles table to find user-profiles, and the platform should query the samples and filter the table to samples where the ispubic variable is true.

**Comment by Jeze2** [comment]
done
