### ISSUE TITLE
Update & Delete Samples

### ISSUE THREAD

**Issue by Matthew-Bustamante** [SampleShare/SampleShare#48]
### Update & Delete Samples
**Description**
Right now the user can't update the name, ispublic, and genre (when implemented).  Also right now the user isn't able to delete their sample from the platform.  So in other words complete CRUD methods for samples

**Requirements**

- The user should be able to update the sample name, the is public field, and the genre (when implemented). The user shouldn't be able to change the sample that is uploaded.
- The user should be able to delete a sample and the sample should be deleted in the database and all other data tied to it.

**Comment by saul178** [comment]
added crud operations for samples, can upload(create), update, and delete. new html to edit samples name, privacy and delete. a new forms for editing sample info only. 2 new urls for editing and deleting. added an edit samples button to the profile page.
took the liberty to also hide usersProfiles when uploading a sample.
